import type { LeadScoreRow, CriativoARC, FunnelAd } from './types';

// ─── Lead Score ────────────────────────────────────────────────────────────────

export const MOCK_LEAD_SCORE_ROWS: LeadScoreRow[] = [
  {
    ad_id: 'ad_001',
    ad_name: 'VSL Rejuvenescimento 45+ | Antes e Depois',
    adset_name: 'Mulheres 40-55 SP',
    campaign_name: 'Metodo Gabriela Rossmann - Escala',
    gasto: 3842.5,
    leads: 147,
    cpl: 26.14,
    resp_pct: 68.3,
    score: 88,
    potencial: 'alto',
    top_drivers: [
      { label: 'Taxa de resposta elevada', value: 68.3, pct: 32 },
      { label: 'CPL abaixo da meta', value: 26.14, pct: 27 },
      { label: 'Engajamento pos-lead', value: 4.2, pct: 21 },
    ],
    top_detractors: [
      { label: 'ROAS abaixo do alvo', value: 1.8, pct: -15 },
      { label: 'CPC elevado mobile', value: 3.4, pct: -10 },
    ],
  },
  {
    ad_id: 'ad_002',
    ad_name: 'Reels Hipopressivo | Dor nas Costas',
    adset_name: 'Mulheres 35-50 RJ',
    campaign_name: 'Metodo Gabriela Rossmann - Escala',
    gasto: 2210.0,
    leads: 98,
    cpl: 22.55,
    resp_pct: 54.1,
    score: 74,
    potencial: 'alto',
    top_drivers: [
      { label: 'CPL otimo', value: 22.55, pct: 40 },
      { label: 'Volume de leads solido', value: 98, pct: 25 },
    ],
    top_detractors: [
      { label: 'Resp. abaixo do ideal', value: 54.1, pct: -20 },
      { label: 'Hold rate fraco (18%)', value: 18.2, pct: -12 },
    ],
  },
  {
    ad_id: 'ad_003',
    ad_name: 'Criativo BN10 Barriga | Depoimento Real',
    adset_name: 'LAL Compradores 3%',
    campaign_name: 'BN10 - Prospeccao Fria',
    gasto: 5120.75,
    leads: 203,
    cpl: 25.22,
    resp_pct: 61.7,
    score: 81,
    potencial: 'alto',
    top_drivers: [
      { label: 'Volume alto de leads', value: 203, pct: 35 },
      { label: 'Resp. acima da media', value: 61.7, pct: 30 },
      { label: 'Audiencia LAL qualificada', value: 3.0, pct: 18 },
    ],
    top_detractors: [
      { label: 'Gasto elevado', value: 5120.75, pct: -18 },
      { label: 'CTR em queda (-0.3pp)', value: 1.2, pct: -8 },
    ],
  },
  {
    ad_id: 'ad_004',
    ad_name: 'Carrossel Beneficios Plano | Saude 2024',
    adset_name: 'MEIs e Autonomos SP',
    campaign_name: 'Planos de Saude - Conversao',
    gasto: 1870.3,
    leads: 61,
    cpl: 30.66,
    resp_pct: 38.5,
    score: 52,
    potencial: 'medio',
    top_drivers: [
      { label: 'Segmentacao precisa', value: 0, pct: 22 },
      { label: 'Criativo educativo', value: 0, pct: 15 },
    ],
    top_detractors: [
      { label: 'CPL acima da meta', value: 30.66, pct: -25 },
      { label: 'Baixa taxa de resposta', value: 38.5, pct: -28 },
      { label: 'Formato carrossel vs video', value: 0, pct: -10 },
    ],
  },
  {
    ad_id: 'ad_005',
    ad_name: 'Story Depoimento | Karina Perdeu 12kg',
    adset_name: 'Interesses Emagrecimento',
    campaign_name: 'BN10 - Prospeccao Fria',
    gasto: 980.0,
    leads: 22,
    cpl: 44.55,
    resp_pct: 27.3,
    score: 31,
    potencial: 'baixo',
    top_drivers: [
      { label: 'Criativo autentico', value: 0, pct: 20 },
    ],
    top_detractors: [
      { label: 'CPL muito alto', value: 44.55, pct: -35 },
      { label: 'Resp. muito baixa', value: 27.3, pct: -30 },
      { label: 'Poucos leads gerados', value: 22, pct: -20 },
    ],
  },
  {
    ad_id: 'ad_006',
    ad_name: 'Imagem Estatica | Preco Plano Familiar',
    adset_name: 'Retargeting Site 30d',
    campaign_name: 'Planos de Saude - Conversao',
    gasto: 450.0,
    leads: 8,
    cpl: 56.25,
    resp_pct: 12.5,
    score: 16,
    potencial: 'desqualificado',
    top_drivers: [],
    top_detractors: [
      { label: 'CPL critico', value: 56.25, pct: -40 },
      { label: 'Taxa de resp. critica', value: 12.5, pct: -35 },
      { label: 'Volume insuficiente', value: 8, pct: -25 },
    ],
  },
  {
    ad_id: 'ad_007',
    ad_name: 'VSL Financas | Saia das Dividas em 90 Dias',
    adset_name: 'Endividados Classe C e D',
    campaign_name: 'Consultoria Financeira - Topo',
    gasto: 2680.0,
    leads: 112,
    cpl: 23.93,
    resp_pct: 49.1,
    score: 63,
    potencial: 'medio',
    top_drivers: [
      { label: 'CPL competitivo', value: 23.93, pct: 30 },
      { label: 'Volume bom de leads', value: 112, pct: 25 },
    ],
    top_detractors: [
      { label: 'Resp. abaixo do alvo', value: 49.1, pct: -22 },
      { label: 'Audiencia fria', value: 0, pct: -15 },
      { label: 'Nicho altamente competitivo', value: 0, pct: -10 },
    ],
  },
];

// ─── Criativos ARC ─────────────────────────────────────────────────────────────

export const MOCK_CRIATIVOS_ARC: CriativoARC[] = [
  {
    ad_id: 'ad_001',
    ad_name: 'VSL Rejuvenescimento 45+ | Antes e Depois',
    campaign_name: 'Metodo Gabriela Rossmann - Escala',
    preview_url: null,
    ad_url: null,
    hook_rate: 42.1,
    hold_rate: 3.8,
    body_rate: 3.2,
    ctr: 2.4,
    roas: 2.1,
    gasto: 3842.5,
    vendas: 7,
    benchmark_atencao: true,
    benchmark_retencao: true,
    benchmark_conversao: true,
  },
  {
    ad_id: 'ad_002',
    ad_name: 'Reels Hipopressivo | Dor nas Costas',
    campaign_name: 'Metodo Gabriela Rossmann - Escala',
    preview_url: null,
    ad_url: null,
    hook_rate: 35.6,
    hold_rate: 2.1,
    body_rate: 1.8,
    ctr: 1.9,
    roas: 1.6,
    gasto: 2210.0,
    vendas: 3,
    benchmark_atencao: true,
    benchmark_retencao: false,
    benchmark_conversao: false,
  },
  {
    ad_id: 'ad_003',
    ad_name: 'Criativo BN10 Barriga | Depoimento Real',
    campaign_name: 'BN10 - Prospeccao Fria',
    preview_url: null,
    ad_url: null,
    hook_rate: 38.9,
    hold_rate: 3.1,
    body_rate: 2.9,
    ctr: 2.1,
    roas: 1.9,
    gasto: 5120.75,
    vendas: 9,
    benchmark_atencao: true,
    benchmark_retencao: true,
    benchmark_conversao: true,
  },
  {
    ad_id: 'ad_004',
    ad_name: 'Carrossel Beneficios Plano | Saude 2024',
    campaign_name: 'Planos de Saude - Conversao',
    preview_url: null,
    ad_url: null,
    hook_rate: 18.4,
    hold_rate: 1.2,
    body_rate: 0.9,
    ctr: 0.8,
    roas: 0.7,
    gasto: 1870.3,
    vendas: 1,
    benchmark_atencao: false,
    benchmark_retencao: false,
    benchmark_conversao: false,
  },
  {
    ad_id: 'ad_005',
    ad_name: 'Story Depoimento | Karina Perdeu 12kg',
    campaign_name: 'BN10 - Prospeccao Fria',
    preview_url: null,
    ad_url: null,
    hook_rate: 28.3,
    hold_rate: 1.9,
    body_rate: 1.4,
    ctr: 1.1,
    roas: 0.9,
    gasto: 980.0,
    vendas: 0,
    benchmark_atencao: false,
    benchmark_retencao: false,
    benchmark_conversao: false,
  },
  {
    ad_id: 'ad_007',
    ad_name: 'VSL Financas | Saia das Dividas em 90 Dias',
    campaign_name: 'Consultoria Financeira - Topo',
    preview_url: null,
    ad_url: null,
    hook_rate: 31.7,
    hold_rate: 2.6,
    body_rate: 2.3,
    ctr: 1.7,
    roas: 1.4,
    gasto: 2680.0,
    vendas: 4,
    benchmark_atencao: true,
    benchmark_retencao: true,
    benchmark_conversao: false,
  },
];

// ─── Funil por Anuncio ─────────────────────────────────────────────────────────
// 10 steps: Impressoes → CPM → CTR → Cliques → CPC → Carregamento → Visitas LP → CPPV → Conversoes → CPA

export const MOCK_FUNNEL_ADS: FunnelAd[] = [
  {
    ad_id: 'ad_001',
    ad_name: 'VSL Rejuvenescimento 45+ | Antes e Depois',
    campaign_name: 'Metodo Gabriela Rossmann - Escala',
    steps: [
      {
        key: 'impressoes',
        label: 'Impressoes',
        value: 184320,
        cost_metric: null,
        cost_label: null,
        conversion_rate: null,
        trend: [158000, 162000, 170000, 175000, 179000, 182000, 184320],
      },
      {
        key: 'cpm',
        label: 'CPM',
        value: 20.85,
        cost_metric: 20.85,
        cost_label: 'R$ 20,85',
        conversion_rate: null,
        trend: [22.1, 21.8, 21.2, 20.9, 21.0, 20.8, 20.85],
      },
      {
        key: 'ctr',
        label: 'CTR',
        value: 2.4,
        cost_metric: null,
        cost_label: '2,4%',
        conversion_rate: 2.4,
        trend: [1.9, 2.0, 2.2, 2.3, 2.3, 2.4, 2.4],
      },
      {
        key: 'cliques',
        label: 'Cliques',
        value: 4424,
        cost_metric: null,
        cost_label: null,
        conversion_rate: null,
        trend: [3000, 3400, 3700, 3950, 4100, 4280, 4424],
      },
      {
        key: 'cpc',
        label: 'CPC',
        value: 0.87,
        cost_metric: 0.87,
        cost_label: 'R$ 0,87',
        conversion_rate: null,
        trend: [1.02, 0.98, 0.94, 0.91, 0.89, 0.88, 0.87],
      },
      {
        key: 'carregamento',
        label: 'Carregamento LP',
        value: 3980,
        cost_metric: null,
        cost_label: null,
        conversion_rate: 89.9,
        trend: [2680, 3050, 3310, 3540, 3720, 3870, 3980],
      },
      {
        key: 'visitas',
        label: 'Visitas LP',
        value: 3210,
        cost_metric: null,
        cost_label: null,
        conversion_rate: 80.7,
        trend: [2150, 2460, 2680, 2850, 3000, 3100, 3210],
      },
      {
        key: 'cppv',
        label: 'CPPV',
        value: 1.2,
        cost_metric: 1.2,
        cost_label: 'R$ 1,20',
        conversion_rate: null,
        trend: [1.55, 1.45, 1.38, 1.30, 1.26, 1.22, 1.2],
      },
      {
        key: 'conversoes',
        label: 'Conversoes',
        value: 147,
        cost_metric: null,
        cost_label: null,
        conversion_rate: 4.58,
        trend: [98, 110, 120, 128, 135, 141, 147],
      },
      {
        key: 'cpa',
        label: 'CPA (CPL)',
        value: 26.14,
        cost_metric: 26.14,
        cost_label: 'R$ 26,14',
        conversion_rate: null,
        trend: [31.2, 29.8, 28.5, 27.6, 27.0, 26.5, 26.14],
      },
    ],
  },
  {
    ad_id: 'ad_003',
    ad_name: 'Criativo BN10 Barriga | Depoimento Real',
    campaign_name: 'BN10 - Prospeccao Fria',
    steps: [
      {
        key: 'impressoes',
        label: 'Impressoes',
        value: 241800,
        cost_metric: null,
        cost_label: null,
        conversion_rate: null,
        trend: [195000, 205000, 215000, 224000, 231000, 237000, 241800],
      },
      {
        key: 'cpm',
        label: 'CPM',
        value: 21.18,
        cost_metric: 21.18,
        cost_label: 'R$ 21,18',
        conversion_rate: null,
        trend: [23.4, 22.8, 22.1, 21.7, 21.4, 21.2, 21.18],
      },
      {
        key: 'ctr',
        label: 'CTR',
        value: 2.1,
        cost_metric: null,
        cost_label: '2,1%',
        conversion_rate: 2.1,
        trend: [1.7, 1.8, 1.9, 2.0, 2.0, 2.1, 2.1],
      },
      {
        key: 'cliques',
        label: 'Cliques',
        value: 5078,
        cost_metric: null,
        cost_label: null,
        conversion_rate: null,
        trend: [3315, 3680, 4030, 4380, 4680, 4900, 5078],
      },
      {
        key: 'cpc',
        label: 'CPC',
        value: 1.01,
        cost_metric: 1.01,
        cost_label: 'R$ 1,01',
        conversion_rate: null,
        trend: [1.22, 1.18, 1.13, 1.08, 1.05, 1.03, 1.01],
      },
      {
        key: 'carregamento',
        label: 'Carregamento LP',
        value: 4420,
        cost_metric: null,
        cost_label: null,
        conversion_rate: 87.1,
        trend: [2885, 3200, 3500, 3800, 4050, 4250, 4420],
      },
      {
        key: 'visitas',
        label: 'Visitas LP',
        value: 3650,
        cost_metric: null,
        cost_label: null,
        conversion_rate: 82.6,
        trend: [2380, 2640, 2890, 3130, 3340, 3510, 3650],
      },
      {
        key: 'cppv',
        label: 'CPPV',
        value: 1.4,
        cost_metric: 1.4,
        cost_label: 'R$ 1,40',
        conversion_rate: null,
        trend: [1.78, 1.68, 1.60, 1.52, 1.47, 1.43, 1.4],
      },
      {
        key: 'conversoes',
        label: 'Conversoes',
        value: 203,
        cost_metric: null,
        cost_label: null,
        conversion_rate: 5.56,
        trend: [130, 148, 162, 174, 185, 195, 203],
      },
      {
        key: 'cpa',
        label: 'CPA (CPL)',
        value: 25.22,
        cost_metric: 25.22,
        cost_label: 'R$ 25,22',
        conversion_rate: null,
        trend: [30.1, 28.9, 27.8, 26.9, 26.2, 25.7, 25.22],
      },
    ],
  },
  {
    ad_id: 'ad_007',
    ad_name: 'VSL Financas | Saia das Dividas em 90 Dias',
    campaign_name: 'Consultoria Financeira - Topo',
    steps: [
      {
        key: 'impressoes',
        label: 'Impressoes',
        value: 127450,
        cost_metric: null,
        cost_label: null,
        conversion_rate: null,
        trend: [102000, 108000, 113000, 118000, 122000, 125000, 127450],
      },
      {
        key: 'cpm',
        label: 'CPM',
        value: 21.03,
        cost_metric: 21.03,
        cost_label: 'R$ 21,03',
        conversion_rate: null,
        trend: [22.8, 22.3, 21.9, 21.6, 21.3, 21.1, 21.03],
      },
      {
        key: 'ctr',
        label: 'CTR',
        value: 1.7,
        cost_metric: null,
        cost_label: '1,7%',
        conversion_rate: 1.7,
        trend: [1.4, 1.5, 1.5, 1.6, 1.6, 1.7, 1.7],
      },
      {
        key: 'cliques',
        label: 'Cliques',
        value: 2167,
        cost_metric: null,
        cost_label: null,
        conversion_rate: null,
        trend: [1428, 1620, 1750, 1880, 1990, 2090, 2167],
      },
      {
        key: 'cpc',
        label: 'CPC',
        value: 1.24,
        cost_metric: 1.24,
        cost_label: 'R$ 1,24',
        conversion_rate: null,
        trend: [1.48, 1.42, 1.38, 1.33, 1.30, 1.27, 1.24],
      },
      {
        key: 'carregamento',
        label: 'Carregamento LP',
        value: 1840,
        cost_metric: null,
        cost_label: null,
        conversion_rate: 84.9,
        trend: [1212, 1374, 1484, 1594, 1690, 1770, 1840],
      },
      {
        key: 'visitas',
        label: 'Visitas LP',
        value: 1502,
        cost_metric: null,
        cost_label: null,
        conversion_rate: 81.6,
        trend: [989, 1122, 1211, 1300, 1380, 1447, 1502],
      },
      {
        key: 'cppv',
        label: 'CPPV',
        value: 1.79,
        cost_metric: 1.79,
        cost_label: 'R$ 1,79',
        conversion_rate: null,
        trend: [2.15, 2.05, 1.98, 1.92, 1.87, 1.83, 1.79],
      },
      {
        key: 'conversoes',
        label: 'Conversoes',
        value: 112,
        cost_metric: null,
        cost_label: null,
        conversion_rate: 7.45,
        trend: [73, 83, 90, 97, 103, 108, 112],
      },
      {
        key: 'cpa',
        label: 'CPA (CPL)',
        value: 23.93,
        cost_metric: 23.93,
        cost_label: 'R$ 23,93',
        conversion_rate: null,
        trend: [28.6, 27.5, 26.6, 25.8, 25.1, 24.5, 23.93],
      },
    ],
  },
];
